from enum import Enum


class TextResolutionSource(str, Enum):
    TEXT_LAYER = "TEXT_LAYER"
    DOCUMENT_VISION_LOCAL = "DOCUMENT_VISION_LOCAL"
    OCR_LOCAL = "OCR_LOCAL"
    CROSS_VERIFIED_VISUAL = "CROSS_VERIFIED_VISUAL"
    UNRESOLVED = "UNRESOLVED"


class VerificationLevel(str, Enum):
    UNVERIFIED = "UNVERIFIED"
    SINGLE_PROVIDER = "SINGLE_PROVIDER"
    CROSS_VERIFIED = "CROSS_VERIFIED"
    CONFLICT = "CONFLICT"
