from enum import Enum


class DocumentType(str, Enum):
    COMMERCIAL_INVOICE = "COMMERCIAL_INVOICE"
    PACKING_LIST = "PACKING_LIST"
    BILL_OF_LADING = "BILL_OF_LADING"
    AIR_WAYBILL = "AIR_WAYBILL"
    CUSTOMS_DECLARATION = "CUSTOMS_DECLARATION"
    CONTRACT = "CONTRACT"
    PURCHASE_ORDER = "PURCHASE_ORDER"
    CERTIFICATE_OF_ORIGIN = "CERTIFICATE_OF_ORIGIN"
    CATALOGUE = "CATALOGUE"
    SPECIFICATION = "SPECIFICATION"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class ClassificationMethod(str, Enum):
    DETERMINISTIC = "DETERMINISTIC"
    LLM_FALLBACK = "LLM_FALLBACK"
